name: Application CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev, staging, prod)'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-nodejs-app
          IMAGE_TAG: latest
        run: |
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/dev-nodejs-app:latest
          format: table
          exit-code: '0'
          severity: CRITICAL,HIGH

      - name: Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-nodejs-app
          IMAGE_TAG: latest
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Fetch DB Secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          SECRET_STRING=$(aws secretsmanager get-secret-value \
            --secret-id dev/rds-credentials94 \
            --query SecretString --output text)
          echo "SECRET_STRING=$SECRET_STRING" >> $GITHUB_ENV

      - name: Parse DB Secrets
        run: |
          echo "DB_USER=$(echo $SECRET_STRING | jq -r .username)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(echo $SECRET_STRING | jq -r .password)" >> $GITHUB_ENV
          echo "DB_HOST=$(echo $SECRET_STRING | jq -r .host)" >> $GITHUB_ENV
          echo "DB_NAME=$(echo $SECRET_STRING | jq -r .dbname)" >> $GITHUB_ENV

      - name: Deploy Application Container
        run: |
          docker run -d \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_HOST=$DB_HOST \
            -e DB_NAME=$DB_NAME \
            -p 80:3000 ${{ steps.login-ecr.outputs.registry }}/dev-nodejs-app:latest
